In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
pd.set_option("display.max_columns",None)
import warnings;
warnings.simplefilter('ignore')
from xgboost import XGBRegressor

In [131]:
train = pd.read_csv(r'C:\Users\Acer\Downloads\train (1)\train.csv')
test = pd.read_csv(r'C:\Users\Acer\Downloads\test (1)\test.csv')

In [132]:
train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  X12  X13  X14  X15  X16  \
0   0  130.81   k  v  at  a  d  u  j  o    0    0    0    1    0    0    0   
1   6   88.53   k  t  av  e  d  y  l  o    0    0    0    0    0    0    0   
2   7   76.26  az  w   n  c  d  x  j  x    0    0    0    0    0    0    0   
3   9   80.62  az  t   n  f  d  x  l  e    0    0    0    0    0    0    0   
4  13   78.02  az  v   n  f  d  h  d  n    0    0    0    0    0    0    0   

   X17  X18  X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  \
0    0    1    0    0    1    0    0    0    0    0    0    0    0    1    0   
1    0    1    0    0    0    0    0    0    0    1    0    0    0    1    0   
2    1    0    0    0    0    0    0    0    0    1    1    1    0    1    0   
3    0    0    0    0    0    0    0    0    0    1    1    1    0    1    0   
4    0    0    0    0    0    0    0    0    0    1    1    1    0    1    0   

   X33  X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  \
0    0    0    1    0    1    0    0    0    0    0    0    0    0    1    0   
1    0    0    1    0    1    0    0    0    0    0    0    0    0    0    0   
2    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   
3    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   
4    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   

   X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  X62  \
0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0   
1    0    0    0    1    0    0    0    0    0    0    0    0    0    1    0   
2    0    0    0    1    0    0    1    0    0    0    1    0    0    1    0   
3    0    0    0    0    0    0    1    0    0    0    0    0    0    1    0   
4    0    0    0    1    0    0    1    0    0    0    0    0    0    1    0   

   X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  X77  X78  \
0    0    0    0    0    0    1    0    1    0    0    1    0    0    0    0   
1    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0   
2    0    0    0    0    0    1    0    1    1    0    1    1    1    0    0   
3    0    0    0    0    0    0    0    1    1    0    1    0    1    0    0   
4    0    0    0    0    0    0    0    1    0    0    1    0    1    0    0   

   X79  X80  X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  X91  X92  X93  \
0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0   
1    0    1    0    0    0    0    1    0    0    0    0    0    0    0    0   
2    0    1    0    0    0    1    1    0    0    0    0    0    0    0    0   
3    0    1    0    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0   

   X94  X95  X96  X97  X98  X99  X100  X101  X102  X103  X104  X105  X106  \
0    0    0    0    0    0    0     0     0     0     0     0     0     0   
1    0    0    1    0    1    0     1     1     0     0     0     0     0   
2    0    0    1    0    1    0     0     1     0     0     0     0     0   
3    0    0    1    0    1    0     0     1     0     0     0     0     0   
4    0    0    1    0    1    0     0     1     0     0     0     0     0   

   X107  X108  X109  X110  X111  X112  X113  X114  X115  X116  X117  X118  \
0     0     0     0     0     1     0     0     1     0     1     0     1   
1     0     0     0     0     1     0     0     0     0     0     0     1   
2     0     0     0     0     1     0     0     0     0     0     0     0   
3     0     1     0     0     1     0     0     1     0     0     0     0   
4     0     1     0     0     1     0     0     1     0     0     0     0   

   X119  X120  X122  X123  X124  X125  X126  X127  X128  X129  X130  X131  \
0     1     1     0     0     0     0     0     0     1     0     0     1   
1     1     1     0     0     0     0     0     1

In [133]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [134]:
#divide data into x and y

In [135]:
y = train['y']
x = train.drop(['y','ID'],axis = 1)
x_test = test.drop(['ID'],axis = 1)

In [136]:
x_train, x_val, y_train, y_val = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [137]:
x_train.head()

X0  X1  X2 X3 X4  X5 X6 X8  X10  X11  X12  X13  X14  X15  X16  X17  X18  \
1006   m   v  as  c  d  ag  k  x    0    0    0    1    1    0    0    0    0   
1840   n   s  as  d  d  ae  g  s    0    0    0    0    1    0    0    0    0   
3792   f   c   m  c  d   v  i  e    0    0    0    0    0    0    0    0    0   
152    j  aa   g  d  d   i  i  e    0    0    0    0    0    0    0    0    0   
1557  ay   i  as  c  d  ad  l  k    0    0    0    0    1    0    0    0    0   

      X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  X33  \
1006    0    0    0    0    0    0    0    1    0    0    0    0    0    0   
1840    0    0    0    0    0    0    0    1    0    0    0    1    0    0   
3792    0    0    0    1    0    0    0    1    0    0    0    0    0    0   
152     0    0    0    0    0    0    0    0    0    0    0    1    0    0   
1557    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

      X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  \
1006    0    0    0    0    0    0    0    0    0    0    0    0    1    0   
1840    0    1    0    1    0    0    0    0    0    0    0    0    1    0   
3792    0    0    0    0    0    0    0    0    0    0    0    0    1    0   
152     0    1    0    1    0    0    0    0    0    0    1    0    1    0   
1557    0    0    0    0    0    0    0    0    0    0    0    1    0    0   

      X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  \
1006    0    1    1    1    0    0    0    0    0    0    1    0    0    1   
1840    0    1    1    1    0    0    0    0    0    0    0    0    0    1   
3792    0    0    0    0    0    0    0    0    0    0    1    0    0    1   
152     0    0    0    1    0    0    0    0    0    0    1    0    0    1   
1557    0    0    0    0    0    0    0    0    0    0    0    0    0    1   

      X62  X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  \
1006    0    0    1    0    0    0    0    0    1    0    0    1    0    0   
1840    0    0    1    0    0    0    0    0    1    1    0    1    0    0   
3792    0    0    1    0    0    0    0    0    1    0    0    1    0    0   
152     0    0    0    0    1    0    1    0    1    0    0    1    0    0   
1557    0    0    0    0    0    0    0    1    0    0    0    1    0    0   

      X77  X78  X79  X80  X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  \
1006    0    0    0    1    0    0    0    0    1    0    0    0    0    0   
1840    0    0    0    1    0    0    0    1    1    0    0    0    0    0   
3792    0    0    0    1    1    0    0    0    1    0    0    0    0    0   
152     0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1557    0    0    0    1    0    0    0    0    0    0    0    0    0    0   

      X91  X92  X93  X94  X95  X96  X97  X98  X99  X100  X101  X102  X103  \
1006    0    0    0    0    0    1    0    1    0     1     1     0     1   
1840    0    0    0    0    0    1    0    1    0     0     1     0     1   
3792    0    0    0    0    0    1    0    1    0     1     1     0     1   
152     0    0    0    0    0    1    0    0    0     0     0     0     0   
1557    0    0    0    0    0    1    0    1    0     0     1     0     0   

      X104  X105  X106  X107  X108  X109  X110  X111  X112  X113  X114  X115  \
1006     0     0     0     0     0     0     0     1     0     0     0     0   
1840     0     0     0     0     0     1     0     1     0     0     1     1   
3792     0     0     0     0     0     0     0     1     0     0     0     0   
152      0     0     0     0     0     0     0     0     1     0     0     0   
1557     0     0     0     0     0     0     0     1     0     0     0     1   

      X116  X117  X118  X119  X120  X122  X123  X124  X125  X126  X127  X128  \
1006     0     0     1     1     1     0     0     0     0     0     1     1   
1840     1     0     0     0     1     0     0     0     0     0     1

In [138]:
numerical_features = x.select_dtypes(include = 'number').columns.values
numerical_features

array(['X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18',
       'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X26', 'X27', 'X28',
       'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37',
       'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46',
       'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55',
       'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64',
       'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X73', 'X74',
       'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83',
       'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92',
       'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101',
       'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109',
       'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117',
       'X118', 'X119', 'X120', 'X122', 'X123', 'X124', 'X125', 'X126',
       'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134',
       'X135',

In [139]:
x_train

X0  X1  X2 X3 X4  X5 X6 X8  X10  X11  X12  X13  X14  X15  X16  X17  X18  \
1006   m   v  as  c  d  ag  k  x    0    0    0    1    1    0    0    0    0   
1840   n   s  as  d  d  ae  g  s    0    0    0    0    1    0    0    0    0   
3792   f   c   m  c  d   v  i  e    0    0    0    0    0    0    0    0    0   
152    j  aa   g  d  d   i  i  e    0    0    0    0    0    0    0    0    0   
1557  ay   i  as  c  d  ad  l  k    0    0    0    0    1    0    0    0    0   
...   ..  ..  .. .. ..  .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3444   j   i  as  c  d   r  l  r    0    0    0    0    1    0    0    0    0   
466   az   y   e  c  d   d  j  j    0    0    0    0    1    0    0    1    0   
3092   y   w  ae  c  d   q  i  c    0    0    0    0    0    0    0    0    0   
3772   y   r  ak  f  d   v  i  b    0    0    1    0    0    0    0    0    0   
860   ba  aa  ai  c  d  af  j  r    0    0    0    0    0    0    0    0    0   

      X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  X33  \
1006    0    0    0    0    0    0    0    1    0    0    0    0    0    0   
1840    0    0    0    0    0    0    0    1    0    0    0    1    0    0   
3792    0    0    0    1    0    0    0    1    0    0    0    0    0    0   
152     0    0    0    0    0    0    0    0    0    0    0    1    0    0   
1557    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3444    0    0    0    0    0    0    0    1    0    0    0    0    0    0   
466     0    0    0    0    0    0    0    1    0    1    0    0    0    0   
3092    0    1    0    0    0    0    0    0    0    0    0    0    0    0   
3772    0    0    0    0    0    0    0    1    0    0    0    0    0    0   
860     1    0    0    0    0    0    0    1    0    0    0    1    0    0   

      X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  \
1006    0    0    0    0    0    0    0    0    0    0    0    0    1    0   
1840    0    1    0    1    0    0    0    0    0    0    0    0    1    0   
3792    0    0    0    0    0    0    0    0    0    0    0    0    1    0   
152     0    1    0    1    0    0    0    0    0    0    1    0    1    0   
1557    0    0    0    0    0    0    0    0    0    0    0    1    0    0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3444    0    0    0    0    0    0    0    0    0    0    0    1    0    0   
466     0    0    0    0    0    0    0    0    0    1    0    0    0    0   
3092    0    0    0    0    0    0    0    0    0    0    0    0    1    0   
3772    0    0    0    0    0    0    0    0    0    0    0    1    0    0   
860     0    1    0    1    0    0    0    0    0    0    0    0    1    0   

      X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  \
1006    0    1    1    1    0    0    0    0    0    0    1    0    0    1   
1840    0    1    1    1    0    0    0    0    0    0    0    0    0    1   
3792    0    0    0    0    0    0    0    0    0    0    1    0    0    1   
152     0    0    0    1    0    0    0    0    0    0    1    0    0    1   
1557    0    0    0    0    0    0    0    0    0    0    0    0    0    1   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3444    0    0    0    1    0    0    0    0    0    0    0    0    0    1   
466     0    0    0    1    0    0    1    0    0    0    0    0    0    1   
3092    0    0    0    1    0    0    0    0    0    0    1    0    0    1   
3772    0    0    0    1    0    0    0    0    0    0    1    0    0    1   
860     0    1    1    0    0    0    0    0    0    0    1    0    0    1   

      X62  X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  \
1006    0    0    1    0    0    0    0    0    1    0    0    1    0    0   
1840    0    0    1    0    0    0    0    0    1    1    0    1  

In [140]:
categorical_features = x.select_dtypes(exclude = 'number').columns.values
categorical_features

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [141]:
oe = OrdinalEncoder(handle_unknown= 'use_encoded_value',unknown_value= np.NaN)
oe.fit(x_train[categorical_features])

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=nan)

In [142]:
x_train[categorical_features] = oe.transform(x_train[categorical_features])
x_val[categorical_features] = oe.transform(x_val[categorical_features])
x_test[categorical_features] = oe.transform(x_test[categorical_features])


In [143]:
x_train[categorical_features]

X0    X1    X2   X3   X4    X5    X6    X8
1006  33.0  23.0  16.0  2.0  3.0   6.0  10.0  23.0
1840  34.0  20.0  16.0  3.0  3.0   4.0   6.0  18.0
3792  26.0   4.0  32.0  2.0  3.0  25.0   8.0   4.0
152   30.0   1.0  27.0  3.0  3.0  13.0   8.0   4.0
1557  18.0  10.0  16.0  2.0  3.0   3.0  11.0  10.0
...    ...   ...   ...  ...  ...   ...   ...   ...
3444  30.0  10.0  16.0  2.0  3.0  22.0  11.0  17.0
466   19.0  25.0  25.0  2.0  3.0   9.0   9.0   9.0
3092  44.0  24.0   3.0  2.0  3.0  21.0   8.0   2.0
3772  44.0  19.0   8.0  5.0  3.0  25.0   8.0   1.0
860   21.0   1.0   7.0  2.0  3.0   5.0   9.0  17.0

[3367 rows x 8 columns]

In [144]:
impute = SimpleImputer(strategy = 'median')
impute.fit(x_train)

SimpleImputer(strategy='median')

In [145]:
x_train = impute.transform(x_train)
x_val = impute.transform(x_val)
x_test = impute.transform(x_test)

In [146]:
x_val

array([[ 8., 16.,  7., ...,  0.,  0.,  0.],
       [26., 13.,  3., ...,  0.,  0.,  0.],
       [30.,  1., 21., ...,  0.,  0.,  0.],
       ...,
       [45.,  1., 21., ...,  0.,  0.,  0.],
       [26., 23.,  3., ...,  0.,  0.,  0.],
       [43., 23., 16., ...,  0.,  0.,  0.]])

In [147]:
x_train

array([[33., 23., 16., ...,  0.,  0.,  0.],
       [34., 20., 16., ...,  0.,  0.,  0.],
       [26.,  4., 32., ...,  0.,  0.,  0.],
       ...,
       [44., 24.,  3., ...,  0.,  0.,  0.],
       [44., 19.,  8., ...,  0.,  0.,  0.],
       [21.,  1.,  7., ...,  0.,  0.,  0.]])

In [148]:
scaler = StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [149]:
x_train = scaler.transform(x_train)
x_val = scaler.transform(x_val)
x_test = scaler.transform(x_test)

In [150]:
x_test

array([[-0.70950621,  1.40241082,  1.52857376, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.74834471, -0.94662643, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.70950621,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.11280744,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-1.58421677,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.74834471, -1.18153016, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143]])

In [151]:
x_val

array([[-1.51132422,  0.58024778, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839,  0.22789219, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.0923118 , -1.18153016,  0.38857645, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.18569999, -1.18153016,  0.38857645, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839,  1.40241082, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 1.0399149 ,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143]])

In [152]:
x_train

array([[ 0.31098943,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.38388198,  1.05005523, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839, -0.82917457,  1.43357399, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.11280744,  1.51986268, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 1.11280744,  0.93260337, -0.84642063, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.56372112, -1.18153016, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143]])

In [153]:
sel = SelectKBest(mutual_info_regression, k=30)
sel.fit(x_train, y_train)

SelectKBest(k=30,
            score_func=<function mutual_info_regression at 0x0000016ADBC8BD80>)

In [154]:
x_test

array([[-0.70950621,  1.40241082,  1.52857376, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.74834471, -0.94662643, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.70950621,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.11280744,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-1.58421677,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.74834471, -1.18153016, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143]])

In [155]:
x_train

array([[ 0.31098943,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.38388198,  1.05005523, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839, -0.82917457,  1.43357399, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.11280744,  1.51986268, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 1.11280744,  0.93260337, -0.84642063, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.56372112, -1.18153016, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143]])

In [156]:
x_val

array([[-1.51132422,  0.58024778, -0.94142041, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839,  0.22789219, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 0.0923118 , -1.18153016,  0.38857645, ..., -0.04225143,
        -0.01723626, -0.04225143],
       ...,
       [ 1.18569999, -1.18153016,  0.38857645, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [-0.19925839,  1.40241082, -1.32141951, ..., -0.04225143,
        -0.01723626, -0.04225143],
       [ 1.0399149 ,  1.40241082, -0.08642243, ..., -0.04225143,
        -0.01723626, -0.04225143]])

#build model

In [157]:
lr = LinearRegression()

In [158]:
lr.fit(x_train, y_train)

LinearRegression()

In [159]:
y_train_pred = lr.predict(x_train)
y_val_pred = lr.predict(x_val)
y_test_pred = lr.predict(x_test)

In [160]:
y_train_pred

array([92.67890067, 89.97298331, 94.16693778, ..., 94.11727042,
       94.22824759, 93.38399405])

In [161]:
y_val_pred

array([ 9.26961431e+01,  9.50057134e+01,  1.14206382e+02,  7.93624486e+01,
        1.08629004e+02,  9.72780218e+01,  9.37217779e+01,  1.07482856e+02,
        1.05444190e+02,  1.10345893e+02,  7.81471929e+01,  9.52039556e+01,
        9.22455663e+01,  1.03930854e+02,  9.38147802e+01,  9.46522893e+01,
        1.09286948e+02,  9.20898199e+01,  9.57367773e+01,  1.13451224e+02,
        1.12265235e+02,  9.19031591e+01,  9.82054052e+01,  1.04264594e+02,
        9.60038824e+01,  1.07680121e+02,  9.46792516e+01,  7.73698492e+01,
        9.45248479e+01,  9.13764257e+01,  9.30258398e+01,  1.04462119e+02,
        9.66729040e+01,  1.11632056e+02,  9.67291936e+01,  1.11845054e+02,
        1.09760581e+02,  9.18172216e+01,  9.30756444e+01,  9.47729253e+01,
        1.12001563e+02,  1.10891791e+02,  9.33153753e+01,  1.10241645e+02,
        9.50060796e+01,  9.31409521e+01,  9.19737310e+01,  1.01845923e+02,
        1.12817466e+02,  1.03523627e+02,  9.31225042e+01,  1.01697349e+02,
        1.06141944e+02,  

In [162]:
y_test_pred

array([2.84645841e+12, 7.81608847e+12, 1.08968661e+02, ...,
       9.22580327e+01, 1.11133246e+02, 9.49525976e+01])

In [163]:
print(r2_score(y_train, y_train_pred))
print(r2_score(y_val, y_val_pred))

0.5927144288042749
-9.404396234267868e+21


In [164]:
submission = pd.DataFrame({
              'ID' :  test['ID'],
              'y' : y_test_pred})
submission.head()

ID             y
0   1  2.846458e+12
1   2  7.816088e+12
2   3  1.089687e+02
3   4  7.894034e+01
4   5  1.094102e+02